---
title: "Generating a graph showing number of women at risk and infected with Mip and each cSTI/RTI"
author: "GGL"
date: "07/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}

```

Load packages (velox package not loading so removed)
```{r}
# List of packages

packages <- c("RColorBrewer", "readxl", "tidyverse", "ggplot2", "cowplot" )

ipak(packages)
```


```{r}
path_numbers_risk_graph <- "/Users/georgiagore-langton/OneDrive - London School of Hygiene and Tropical Medicine/PhD_1/R/20200706_number at risk flow diagram"

path_save <- "/Users/georgiagore-langton/OneDrive - London School of Hygiene and Tropical Medicine/PhD_1/Upgrading/Upgrading Report"

```

```{r}
numbers <- read_excel(paste(path_numbers_risk_graph, "20200706_MIP_STI_numbers_to_plot.xlsx", sep="/"))
```
```{r}
numbers <- numbers %>% mutate(n_plot = round(n/1000000, 2), 
                              n_plot2 = paste(as.character(n_plot), "M", sep=" "))
```

```{r}
numbers$prev <- (numbers$prev*100)
numbers$prev <- format(round(numbers$prev,2), nsmall = 2) 
numbers$prev <- paste(as.character(numbers$prev), "%", sep = " ")

# make label show % prevalence rather than nmber of women for all but total number at risk
numbers <- numbers %>% mutate(n_label = if_else(ref=="PhD Objective One", n_plot2, prev))
                                       
```

# adding superscript to variables to denote references
```{r}
numbers <- numbers %>% mutate(var_ref = if_else(ref=="PhD Objective One", paste(as.character(var), "*", sep=""),  
                              if_else(ref=="World Malaria Report 2018", paste(as.character(var), "**", sep=""), 
                                      if_else(ref=="Chico et al. JAMA", paste(as.character(var), "***", sep="" ), 
                                              if_else(ref=="Chaponda et al. ASTMH", paste(as.character(var), "****", sep=""), "NA")))))
```


# all left aligned
```{r}

plot <- numbers %>% 
ggplot(., aes(n_plot, y, colour = var)) +
 geom_path() +
  geom_text(aes(label=ifelse(n==0,as.character(var_ref),'')),hjust=0, vjust=-0.4) + 
geom_text(aes(size= , label=ifelse(n!=0,as.character(n_label),'')),hjust=0, vjust=1) + 
theme(legend.position = "none") + theme(axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),legend.position="none",
          panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),plot.background=element_blank())+ 
    scale_x_continuous(expand = c(.15, .15))+ 
    scale_y_continuous(expand = c(.15, .15))

plot + scale_color_manual(values = c("aquamarine3", "aquamarine3", "dodgerblue3", "dodgerblue3", "aquamarine3", "dodgerblue3", "brown3", "dodgerblue3", "aquamarine3", "dodgerblue3"))


```


# mixing up infection positioning - Version 1
```{r}

numbers2 <- numbers %>% mutate(n_plot_mix = if_else(var == "Co-infection", n_plot + 20,
                                                   if_else(var == "MiP", n_plot + 20,
                                                        if_else(var == "BV", n_plot + 15, 
                                                                 if_else(var == "TV", n_plot + 22,
                                                                          if_else(var == "Chlamydia", n_plot + 25,
                                                                                   if_else(var == "Gonorrheae", n_plot + 22,
                                                                                       if_else(var == "Syphillis", n_plot + 24,
                                                                                               n_plot)))))))) 

```

# plot with overlap of infections mixed 

```{r}

plot2 <- numbers2 %>% 
ggplot(., aes(n_plot_mix, y, colour = var)) +
 geom_path() +
  geom_text(aes(label=ifelse(n==0,as.character(var_ref),'')),hjust=0, vjust=-0.4) + 
geom_text(aes(size= , label=ifelse(n!=0,as.character(n_label),'')),hjust=0, vjust=1) + 
theme(legend.position = "none") + theme(axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),legend.position="none",
          panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),plot.background=element_blank())+ 
    scale_x_continuous(expand = c(.15, .15))+ 
    scale_y_continuous(expand = c(.15, .15))

plot2 <- plot2 + scale_color_manual(values = c("aquamarine3", "aquamarine3", "dodgerblue3", "dodgerblue3", "aquamarine3", "dodgerblue3", "brown3", "dodgerblue3", "aquamarine3", "dodgerblue3"))



```

# mixing up infection positioning - Version 2
```{r}

numbers3 <- numbers %>% mutate(n_plot_mix = if_else(var == "MiP", n_plot + 13,
                                                        if_else(var == "BV", n_plot + 2, 
                                                                 if_else(var == "TV", n_plot + 18,
                                                                          if_else(var == "Chlamydia", n_plot + 30,
                                                                                   if_else(var == "Gonorrheae", n_plot + 0,
                                                                                       if_else(var == "Syphillis", n_plot + 7,
                                                                                               n_plot)))))))

```

# plot with overlap of infections mixed 

```{r}

plot3 <- numbers3 %>% 
ggplot(., aes(n_plot_mix, y, colour = var)) +
 geom_path() +
  geom_text(aes(label=ifelse(n==0,as.character(var_ref),'')),hjust=0, vjust=-0.4) + 
geom_text(aes(size= , label=ifelse(n!=0,as.character(n_label),'')),hjust=0, vjust=1) + 
theme(legend.position = "none") + theme(axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),legend.position="none",
          panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),plot.background=element_blank())+ 
    scale_x_continuous(expand = c(.15, .15))+ 
    scale_y_continuous(expand = c(.15, .15))

plot3 <- plot3 + scale_color_manual(values = c("aquamarine3", "aquamarine3", "dodgerblue3", "dodgerblue3", "aquamarine3", "dodgerblue3", "brown3", "dodgerblue3", "aquamarine3", "dodgerblue3"))



```

```{r}
# combine the over lapping and not at all overlapping plots for upgrading report 

plotgrid <- plot_grid(plot3, plot2, labels = c('A', 'B'), ncol = 1, label_size = 12)
plotgrid

ggsave(paste(path_save, "numbers_infected_overlap.pdf", sep="/"))

```

